TELEGRAM_TOKEN = "REPLACE_WITH_TELEGRAM_BOT_TOKEN"
OPENAI_API_KEY = "REPLACE_WITH_OPENAI_API_KEY"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
EMAIL_LOGIN = "REPLACE_WITH_EMAIL_LOGIN"
EMAIL_PASSWORD = "REPLACE_WITH_EMAIL_APP_PASSWORD"
